language: android
android:
  components:
    - build-tools-25.0.2
    - android-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17
    - sys-img-x86_64-google_apis-25

script: ./gradlew build