language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-25.0.2
    - android-25
    - tools

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17
    - sys-img-x86_64-google_apis-25

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script: ./gradlew build